# [Prof. Dalvan Griebler](mailto:dalvan.griebler@pucrs.br)

## Programação Orientada a Dados (POD) - Turma 10 (POD_98H04-06)

**Atualizado**: 28/10/2021

**Descrição**: Exercícios com NumPy para POD.

**Copyright &copy;**: Este documento está sob a licensa da Criative Commons [BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode)

**Resolvido por:**

In [2]:
import numpy as np

**1. Crie um `ndarray` a partir da lista e depois altere para booleano. Ao final, conte quantos elementos são verdadeiros e quantos são falsos.**

```python
lista = [[1, 2, 3], [0, 5, 0], [10, -1, -3], [0, 50, 0]]
```

In [16]:
lista = [[1, 2, 3], [0, 5, 0], [10, -1, -3], [0, 50, 0]]

arr = np.array(lista, dtype=bool)

print(f'True: {np.count_nonzero(arr==True)} False: {np.count_nonzero(arr==False)}')

True: 8 False: 4


**2. Crie um `ndarray` com tamanho 5x5 contendo apenas zeros. Em seguida, realize operações de indexação/slicing para obter o seguinte array:**

```python
[[0. 8. 0. 0. 0.]
 [0. 8. 0. 2. 2.]
 [5. 5. 5. 5. 0.]
 [0. 8. 0. 2. 2.]
 [0. 8. 0. 0. 0.]]
 ```

In [10]:
mtx = np.zeros(25).reshape(5,5)
mtx[:,1] = 8
mtx[2,:4] = 5
mtx[1,3:] = 2
mtx[3, 3:] = 2

mtx

array([[0., 8., 0., 0., 0.],
       [0., 8., 0., 2., 2.],
       [5., 5., 5., 5., 0.],
       [0., 8., 0., 2., 2.],
       [0., 8., 0., 0., 0.]])

**3. Dado o array `a`, some 10 em todos os elementos de sua Penúltima coluna e linha.**

In [19]:
mtx = np.zeros(25).reshape(5,5)

mtx[3,:] = 2
mtx[:, 3] = 2

print(mtx[3, :].sum(), mtx[:, 3].sum())

10.0 10.0


**4. Dado o array `a`, realize as seguintes operações:**
  - Crie um array `b` de mesmo tamanho que `a`, onde todos os valores são 10
  - Realize a soma de `a` e `b`.
  - Multiplique todos os elementos do array resultante por 100
  
  ```python
    a = np.arange(10, 70, 3).reshape(4, 5)
  ```

In [26]:
a = np.arange(10, 70, 3).reshape(4, 5)
b = np.full((4,5), 10)

c = (a + b) * 100
c

array([[2000, 2300, 2600, 2900, 3200],
       [3500, 3800, 4100, 4400, 4700],
       [5000, 5300, 5600, 5900, 6200],
       [6500, 6800, 7100, 7400, 7700]])

**5. Crie um array 2D com a sequência de números ímpares no intervalo 0 a 100 e faça as seguintes operações:**
- Média das linhas
- Média das colunas
- Soma dos elementos da última linha
- Soma dos elementos da última coluna

In [38]:
mtx = np.arange(1, 100, 2).reshape(5, 10)
print(mtx)

print(f'mean lines:{np.mean(mtx, axis=1)}')
print(f'mean columns:{np.mean(mtx, axis=0)}')
print(f'sum of last line:{mtx[-1,:].sum()}')
print(f'sum of last column:{mtx[:, -1].sum()}')

[[ 1  3  5  7  9 11 13 15 17 19]
 [21 23 25 27 29 31 33 35 37 39]
 [41 43 45 47 49 51 53 55 57 59]
 [61 63 65 67 69 71 73 75 77 79]
 [81 83 85 87 89 91 93 95 97 99]]
mean lines:[10. 30. 50. 70. 90.]
mean columns:[41. 43. 45. 47. 49. 51. 53. 55. 57. 59.]
sum of last line:900
sum of last column:295


**6. Crie um array com a seguinte estrutura:**

```bash
[[ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]
 [10 20 30 40 50]]
```

In [66]:
mtx = np.zeros(50, dtype=int).reshape(10,5)
mtx[:, 0] = np.arange(1,11,1)
mtx[:, 1] = np.arange(11,21,1)
mtx[:, 2] = np.arange(21,31,1)
mtx[:, 3] = np.arange(31,41,1)
mtx[:, 4] = np.arange(41,51,1)

mtx

array([[ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44],
       [ 5, 15, 25, 35, 45],
       [ 6, 16, 26, 36, 46],
       [ 7, 17, 27, 37, 47],
       [ 8, 18, 28, 38, 48],
       [ 9, 19, 29, 39, 49],
       [10, 20, 30, 40, 50]])

**7. Crie uma array com a seguinte estrutura:**

```bash
[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  0 -1  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  1]
 [ 1  1  1  1  1  1  1  1  1  1]]
```

In [65]:
mtx = np.zeros(100, dtype=int).reshape(10,10)
mtx[:, 0] = 1
mtx[0, 1:] = 1
mtx[-1, 1:] = 1
mtx[1:-1, -1] = 1
mtx[5, 5] = -1

mtx

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 1,  0,  0,  0,  0, -1,  0,  0,  0,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

**8. Crie um array 2D `shape(8,8)` com os seguintes valores.**
```bash
[[ 0. -1.  0.  0. -1.  0.  0. -1.]
 [-1.  0.  0. -1.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0. -1.  0.  0. -1.]
 [-1.  0.  0. -1.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0. -1.  0.  0. -1.]
 [-1.  0.  0. -1.  0.  0. -1.  0.]]
```

In [73]:
mtx = np.zeros(64).reshape(8,8)

mtx[0::3, 1::3] = -1
mtx[1::3, ::3] = -1

mtx

array([[ 0., -1.,  0.,  0., -1.,  0.,  0., -1.],
       [-1.,  0.,  0., -1.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0., -1.,  0.,  0., -1.],
       [-1.,  0.,  0., -1.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0., -1.,  0.,  0., -1.],
       [-1.,  0.,  0., -1.,  0.,  0., -1.,  0.]])

**9. Dados um array `a`, realize operações de slicing para obter os arrays `b,c,d,e`.**
```python
a = np.arange(1, 51).reshape(5, 10)
```

```bash
b: 
 [12 13 14 15]
c: 
 [ 4 14 24 34 44]
d: 
 [[32 33 34 35 36 37]
 [42 43 44 45 46 47]]
e: 
 [[30 28 26 24 22]
 [50 48 46 44 42]]
```

**10. Crie um array 2D em que a soma da quinta e décima colunas produzem o resultado `340` e a média a partir da terceira linha até o fim produz o resultado `53`.**

**11. Dado um array `a`:**
  - Imprima os elementos de cada coluna de maneira crescente.
  - Imprima os elementos de cada linha de maneira decrescente.
  ```python
a = np.array([[1, 22, 8, 9, 12, 33],
                [11, 51, 13, 8, 13, 2],
                [10, 0, 1, 8, 8, 5],
                [0, 12, 23, 14, 2, 16],
                [1, 13, 17, 8, 10, 1]])
  ```

**12. Dado um array `a`:**
  - Imprima o menor valor do array
  - Imprima o maior valor da coluna 2
  - Imprima os menores valores para cada linha
  - Imprima a posição (em 2D) do maior valor
  
    ```python
a = np.array([[1, 22, 8, 9, 12, 33],
                [11, 51, 13, 8, 13, 2],
                [10, 0, 1, 8, 8, 5],
                [0, 12, 23, 14, 2, 16],
                [1, 13, 17, 8, 10, 1]])
  ```

**13. Particione verticalmente ao meio o array `a`, armazenando a parte superior em `b` e inferior em `c`. Depois, tranforme os números negativos em positivos do array `c` e atribua `0` para os valores negativos do array `b`. Ao final das transformações, concatene `b` com `c` e forneça a matriz transposta.**
```python
a=np.random.randn(6, 6)
```

**14. Crie um programa que gera números pseudo aleatorios com semente `3000` para um array `a` de `shape(10,10)` e outro array `b` de `shape(10,5)` usando semente `1234` e depois escreva o resultado em um arquivo `.npz`. Então, leia do arquivo os dois arrays `a` e `b`. Para realizar as sequintes operações, no `b` selecione apenas a terceira coluna. Ao final do programa, salve em um arquivo comprimido o resultado das operações.**
- a * b
- a / b
- a - b
- a + b