In [2]:
import numpy as np

In [3]:
X = np.asarray([[.5, .2], [.1, .6]])
y = np.asarray([.7, .8])
w1 = np.asarray([[.5, .2], [.6, -.1],[-.4, -.3]])
w2 = np.asarray([[.7, -.1, .2]])

In [23]:
def sigmoid(x):
    return 1/(1 + pow(np.e, -x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

def loss(yh, y):
    return (1/2) * sum(pow(yh - y, 2).flatten())

In [5]:
#Layer 1
s1 = np.dot(w1, X[:,[0]])
print(s1)
s1 = sigmoid(s1)
print(s1)

[[ 0.27]
 [ 0.29]
 [-0.23]]
[[0.5670929 ]
 [0.57199613]
 [0.44275215]]


In [8]:
#Layer 2
s2 = np.dot(w2, s1)
print(s2)
s2 = sigmoid(s2)
print(f'sigmoid: {s2}')

[[0.42831585]]
sigmoid: [[0.60547144]]


In [7]:
#Loss 
J = loss(s2, y[0])
print(J)

0.004467824596205634


In [10]:
#Backwarpass DJ/DO
s2 - y[0]

array([[-0.09452856]])

In [11]:
#Backwarpass DO/DS
s2 * (1 - s2)

array([[0.23887578]])

In [42]:
dt2 = s2 * (1 - s2) * (s2 - y[0])
dt2

array([[-0.02258058]])

In [43]:
bp1 = np.dot(sigmoid_derivative(s2), s2 * (1 - s2) * (s2 - y[0])* w2)
print('backwardpass1: ', bp1)

X[:,0] * bp1.T

s1 * dt2

backwardpass1:  [[-0.00361047  0.00051578 -0.00103156]]


array([[-0.01280529],
       [-0.01291601],
       [-0.0099976 ]])

In [34]:
bp1

array([[-0.00361047,  0.00051578, -0.00103156]])

In [24]:
sigmoid_derivative(s1)

array([[0.23093057],
       [0.23061678],
       [0.23813761]])