# [Prof. Dalvan Griebler](mailto:dalvan.griebler@pucrs.br)

## Programação Orientada a Dados (POD) - Turma 10 (POD_98H04-06)

**Atualizado**: 17/11/2022

**Descrição**: Trabalho Individual: Manipulação, Análise e Visualização Vetorial e Tabular de Dados

**Copyright &copy;**: Este documento está sob a licensa da Criative Commons [BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode)

**_Atenção: Pontuação extra para quem explicar como funcionam as partes dos códigos para resolver cada questão através de comentário do Python (`#`)._**

**_Atenção: O resultado deverá ser igual ao resultado esperado._**

### Trabalho realizado por:

Cristiano Moreira Martins

# Bibliotecas Autorizadas

Não importe outras bibliotecas além destas, pois não estão autorizadas para o uso.

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from PIL import Image

# Parte-1: Manipulação de Dados Vetorial e Geração de Gráficos Simples

_Atenção: não será permitido o uso de laços nesta parte do trabalho sobre manipulação vetorial._

## 1. Crie um array 2D `shape(10,10)`  e realize operações de indexação e fatiamento para obter o seguinte resultado.

```bash
   [[ 1.,  2.,  3.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
    [ 2.,  1.,  2.,  3., 10., 10., 10., 10., 10., 10.],
    [ 3.,  2.,  1.,  2.,  3., 15., 15., 15., 15., 15.],
    [ 5.,  3.,  2.,  1.,  2.,  3., 20., 20., 20., 20.],
    [ 5., 10.,  3.,  2.,  1.,  2.,  3., 25., 25., 25.],
    [ 5., 10., 15.,  3.,  2.,  3.,  2.,  3., 30., 30.],
    [ 5., 10., 15., 20.,  3.,  2.,  3.,  2.,  3., 35.],
    [ 5., 10., 15., 20., 25.,  3.,  2.,  3.,  2.,  3.],
    [ 5., 10., 15., 20., 25., 30.,  3.,  2.,  3.,  2.],
    [ 5., 10., 15., 20., 25., 30., 35.,  3.,  2.,  3.]]
    
```

In [48]:
matrix = np.ones(100).reshape(10, 10)
matrix[0, 3:] = 5
matrix[1, 4:] = 10
matrix[2, 5:] = 15
matrix[3, 6:] = 20
matrix[4, 7:] = 25
matrix[5, 8:] = 30
matrix[6, 9:] = 35

matrix[3:, 0] = 5
matrix[4:, 1] = 10
matrix[5:, 2] = 15
matrix[6:, 3] = 20
matrix[7:, 4] = 25
matrix[8:, 5] = 30
matrix[9:, 6] = 35

#altera os valores nas diagonais
np.fill_diagonal(matrix[1:], 2)
np.fill_diagonal(matrix[:, 1:], 2)
np.fill_diagonal(matrix[2:], 3)
np.fill_diagonal(matrix[:, 2:], 3)
np.fill_diagonal(matrix[5:, 5:], 3)

print(matrix)


[[ 1.  2.  3.  5.  5.  5.  5.  5.  5.  5.]
 [ 2.  1.  2.  3. 10. 10. 10. 10. 10. 10.]
 [ 3.  2.  1.  2.  3. 15. 15. 15. 15. 15.]
 [ 5.  3.  2.  1.  2.  3. 20. 20. 20. 20.]
 [ 5. 10.  3.  2.  1.  2.  3. 25. 25. 25.]
 [ 5. 10. 15.  3.  2.  3.  2.  3. 30. 30.]
 [ 5. 10. 15. 20.  3.  2.  3.  2.  3. 35.]
 [ 5. 10. 15. 20. 25.  3.  2.  3.  2.  3.]
 [ 5. 10. 15. 20. 25. 30.  3.  2.  3.  2.]
 [ 5. 10. 15. 20. 25. 30. 35.  3.  2.  3.]]


## 2. Para o seguinte array, calcule: 
- Médias das diagonais principal e secundária.
- Média das linhas e coluna para posteriomente plotar um gráfico de linhas.

```python
 np.array([[ 44,  70,  98,  63,  30,  96,  26,  94,  20,  67],
       [ 22,  79,  53,  16,  46,  63,  45,  61,  66,  10],
       [ 71,  96,  68,  14,  86,  99,   1,  44,  66,  20],
       [ 92,  40,   0,  12,  91,   1,   9,  19,  60,   5],
       [ 53,  46,  65,  73,  29,   0,  89, 100,  13,  78],
       [ 81,  16,  21, 100,  36,  51,  38,  85,  90,  35],
       [ 91,  70,   8,  20,  60,  40,  14,  16,   0,  19],
       [ 87,  10,  24,  40,  62,   5,  32,  28,  69,  29],
       [ 94,  88,  40,   4,  85,  61,  30,  68,  63,  61],
       [ 74, 100,  34,  88,   0,  12,  61,  32,  10,  46]])
```

**Resultado esperado:**

Média diagonal principal:  43.4

Média diagonal secundária:  42.8


![](fig-ti2-ex2.png)

In [ ]:
mtx_2 = np.array([
    [ 44,  70,  98,  63,  30,  96,  26,  94,  20,  67],
    [ 22,  79,  53,  16,  46,  63,  45,  61,  66,  10],
    [ 71,  96,  68,  14,  86,  99,   1,  44,  66,  20],
    [ 92,  40,   0,  12,  91,   1,   9,  19,  60,   5],
    [ 53,  46,  65,  73,  29,   0,  89, 100,  13,  78],
    [ 81,  16,  21, 100,  36,  51,  38,  85,  90,  35],
    [ 91,  70,   8,  20,  60,  40,  14,  16,   0,  19],
    [ 87,  10,  24,  40,  62,   5,  32,  28,  69,  29],
    [ 94,  88,  40,   4,  85,  61,  30,  68,  63,  61],
    [ 74, 100,  34,  88,   0,  12,  61,  32,  10,  46]])


#media da diagonal principal
print(f'Média diagonal principal: {mtx_2.diagonal().mean()}')

#media da diagonal secundária
print(f'Média diagonal secundária: {mtx_2[::-1].diagonal().mean()}')

#media de cada linha
mtx_2_lm = mtx_2.mean(axis=0)

#media de cada coluna
mtx_2_cm = mtx_2.mean(axis=1)


#plot linhas e colunas
plt.plot(mtx_2_lm, label='linhas', marker='^', color='chocolate')
plt.plot(mtx_2_cm, label='colunas', marker='o', color='blue')
plt.legend()
plt.xlabel('Colunas')
plt.ylabel('Médias')
plt.title('Resultados')
plt.show()


# Parte-2: Manipulação de Dados Tabular

## 3. Forneça um único DataFrame a partir dos dados contidos em `cars_info.csv` e `cars_valores.csv`. Depois salve o DataFrame em um arquivo chamado `cars.csv` para reusar nas próximas questões.

_Obs: Para quem usar laços nesta questão, terá um desconto de 25% na nota._


**Resultado Esperado do DataFrame:**
```bash
<class 'pandas.core.frame.DataFrame'>
Int64Index: 4340 entries, 0 to 4339
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   ID             4340 non-null   int64 
 1   name           4340 non-null   object
 2   fuel           4340 non-null   object
 3   seller_type    4340 non-null   object
 4   transmission   4340 non-null   object
 5   owner          4340 non-null   object
 6   year           4340 non-null   int64 
 7   selling_price  4340 non-null   object
 8   km_driven      4340 non-null   int64 
dtypes: int64(3), object(6)
```

In [3]:
#realiza a leitura dos arquivos
car_info = pd.read_csv('CAR_INFO.csv').set_index('ID')
car_values = pd.read_csv('CAR_VALUES.csv').set_index('ID')

#remove a coluna name de car_values para nao ter que remover após o merge
car_values.drop('name', axis=1, inplace=True)

#realiza o merge dos dois dataframes
cars = pd.concat([car_info, car_values], axis=1, join='inner')

#salva o csv com o merge dos arquivos
cars.to_csv('cars.csv')


## 4 - Adicione o campo `marca` no `cars.csv` e corrija os dados.

_Obs: o valor do campo marca deve ser extraído de uma coluna do próprio dataset_

_Obs: Atente-se aos dados faltantes no campo selling-price, eles devem ser preenchidos com a média de preço dos carros da mesma marca_

**Resultado Esperado do DataFrame:**


```bash
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   ID             4340 non-null   int64 
 1   name           4340 non-null   object
 2   fuel           4340 non-null   object
 3   seller_type    4340 non-null   object
 4   transmission   4340 non-null   object
 5   owner          4340 non-null   object
 6   year           4340 non-null   int64 
 7   selling_price  4340 non-null   int64 
 8   km_driven      4340 non-null   int64 
 9   marca          4340 non-null   object
dtypes: int64(4), object(6)
```

In [4]:
#realiza a leitura do arquivo
cars = pd.read_csv('cars.csv').set_index('ID')

#adiciona o nome da marca, realizando um split no campo name e extraindo o primeiro valor da lista resultante
cars['marca'] = cars['name'].str.split(' ')[:].str[0]

#para cada marca...
for m in cars['marca'].unique():
    #calcula a média de preço de venda para a marca
    marca_avg = round(cars[cars['marca'] == m]['selling_price'].str.split(' ').str[1].astype('int').mean())
    
    #ajusta o campo selling_price que tem o valor zero para o valor da média calculada conforme a marca
    cars.loc[(cars['selling_price'] == '€ 0') & (cars['marca'] == m), 'selling_price'] = f'€ {marca_avg}'


#sava o arquivo com os valores ajustados
cars.to_csv('cars.csv')

## 5- Mostre a diferença de preço de venda entre `First Owner` e `Second Owner` dos top 5 marcas mais caras pelo preço médio em gráfico de barras do dataset `cars.csv`.

**Resultado Esperado**

![](fig-ti2-ex5.png)


In [ ]:
cars = pd.read_csv('cars.csv').set_index('ID')

#ajusta o tipo do preço de venda para número
cars['selling_price'] = cars['selling_price'].str.split(' ').str[1].astype('float')

#filtra as cinco marcas com maior média de preço de venda
marcas_avg = cars.groupby(by='marca')[['selling_price']].mean().reset_index()\
    .sort_values(by=['selling_price'], ascending=False).head(5)\
    .sort_values(by=['marca'])

#calcula a média de preço das cinco marcas para o first owner
first_owner = cars[(cars['owner'] == 'First Owner') & (cars['marca'].isin(marcas_avg['marca']))]\
    [['selling_price', 'marca']].groupby('marca').mean().sort_values(by='marca', ascending=True)

#calcula a média de preço das cinco marcas para o second owner
second_owner = cars[(cars['owner'] == 'Second Owner') & (cars['marca'].isin(marcas_avg['marca']))]\
    [['selling_price', 'marca']].groupby('marca').mean().sort_values(by='marca', ascending=True)

#ajusta o nome da coluna de preço conforme o owner
first_owner.rename(columns={'selling_price': 'first_owner'}, inplace=True)
second_owner.rename(columns={'selling_price': 'second_owner'}, inplace=True)

#cria um dataframe com os dados consolidados e ajusta o formato dos valores
owners = pd.concat([first_owner, second_owner], axis=1).fillna(0).applymap(lambda x: round(x, 2))

#remove os dataframes auxiliares
del(first_owner, second_owner, marcas_avg)

In [ ]:
#plota o grafico
width = .35
position = np.arange(len(owners['first_owner']))

plt.subplots(figsize=(10, 4))
fo_bars = plt.bar(position, owners['first_owner'], label='First Owner', color='red', width=width)
so_bars = plt.bar(position + width + .02, owners['second_owner'], label='Second Owner', color='blue', width=width)

plt.xticks(position + width / 2, owners.index)
for bar in fo_bars:
    bh = bar.get_height()
    plt.text(bar.get_x() - .08, bh, '{:.2f}'.format(bh), va='bottom')

for bar in so_bars:
    bh = bar.get_height()
    plt.text(bar.get_x()- .08, bh, '{:.2f}'.format(bh), va='bottom')


plt.xlabel('Marcas')
plt.ylabel('Preço médio (em milhões)')
plt.title('Preço médio das 5 marcas com preço médio mais alto')
plt.legend()
plt.show()

## 6- Mostre em gráfico de pizza (`Axes(1,2)`) com os 5 anos de maior número de vendas de carros usados (`Second Owner`) e maior número de vendas de carros novos (`First Owner`).

**Resultado Esperado**

![](fig-ti2-ex6.png)

In [ ]:
cars = pd.read_csv('cars.csv').set_index('ID')

#calcula a quantidade de vendas por ano como first owner e second owner
first_owner = cars[cars['owner'] == 'First Owner'][['selling_price', 'year']].groupby('year').count().reset_index()
second_owner = cars[cars['owner'] == 'Second Owner'][['selling_price', 'year']].groupby('year').count().reset_index()

#captura os anos com maior percentual de vendas para first owner e second owner
first_owner = first_owner.sort_values(by='selling_price', ascending=False).head(5)
second_owner = second_owner.sort_values(by='selling_price', ascending=False).head(5)

#calcula o percentual de vendas relativo aos cinco primeiros anos de first owner e second owner
first_owner['percent'] = round(first_owner['selling_price'] / first_owner['selling_price'].sum() * 100, 2)
second_owner['percent'] = round(second_owner['selling_price'] / second_owner['selling_price'].sum() * 100, 2)

#plota os graficos de pizza para first owner e second owner
fig, ax = plt.subplots(1, 2, figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.pie(second_owner['percent'], labels=second_owner['year'], autopct='%.2f%%', explode=[0.15, 0, 0, 0, 0])
plt.title('Vendas como second owner')

plt.subplot(1, 2, 2)
plt.pie(first_owner['percent'], labels=first_owner['year'], autopct='%.2f%%', explode=[0.15, 0, 0, 0, 0])
plt.title('Vendas como first owner')

plt.show()

## 7. Para a base de dados `cars.csv`, apresente dois gráficos `boxplot`  (`Axes(1,2)`) do valor de `km_driven`, sendo um para os 5 mais vendidos como `First Owner` e outro para os 5 mais vendidos como `Second Owner`.

**Resultado Esperado**

![](fig-ti2-ex7.png)

In [5]:
cars = pd.read_csv('cars.csv').set_index('ID')

#captura os 5 mais vendidos para first owner e second owner
top_first_owner = cars[cars['owner'] == 'First Owner'][['km_driven', 'name']].groupby('name').count().reset_index()\
    .sort_values(by='km_driven', ascending=False).head(5)

top_second_owner = cars[cars['owner'] == 'Second Owner'][['km_driven', 'name']].groupby('name').count().reset_index()\
    .sort_values(by='km_driven', ascending=False).head(5)

first_owner = cars[cars['name'].isin(top_first_owner['name']) & (cars['owner'] == 'First Owner')][['km_driven', 'name']]
second_owner = cars[cars['name'].isin(top_second_owner['name']) & (cars['owner'] == 'Second Owner')][['km_driven', 'name']]



In [ ]:
#plota os graficos boxplot de km_driven e name para first owner e second owner

#https://matplotlib.org/stable/gallery/statistics/boxplot_color.html

fig, ax = plt.subplots(1, 2, figsize=(10, 4))




plt.subplot(1, 2, 1)
plt.boxplot(first_owner['km_driven'])
plt.title('Mais vendidos como first owner')

#plt.subplot(1, 2, 2)
#plt.boxplot(second_owner)
#plt.title('Mais vendidos como second owner')


plt.show()



In [ ]:
#cars.loc[(cars['selling_price'] == '€ 0') & (cars['marca'] == m), 'selling_price'] = f'€ {marca_avg}'
name = 'Maruti Alto LXi'
top_first_owner.loc[top_first_owner['name'] == name , 'values'] = first_owner[first_owner['name'] == name]['km_driven']


In [ ]:
data = pd.DataFrame()
for name in top_first_owner['name'].values:
    temp = {
        'name': name,
        'km_driven': list(first_owner[first_owner['name'] == name]['km_driven'].values)
    }

    temp = pd.DataFrame(temp)
    data = pd.concat([data, temp], axis=0)

data

In [ ]:
# Pandas dataframe
data = pd.DataFrame({"Box1": np.random.rand(10), "Box2": np.random.rand(10)})

# Plot the dataframe
ax = data[['Box1', 'Box2']].plot(kind='box', title='boxplot')

# Display the plot
plt.show()